version: "3.3"
networks:
  spark-network:
services:
  spark-master:
    image: qwertyjack/spark
    container_name: spark-master
    hostname: spark-master
    command: >
      /bin/sh -c '
      /spark/sbin/start-master.sh
      && tail -f /spark/logs/*'
    ports:
      - 8080:8080
      - 4040-4050:4040-4050
    networks:
      - spark-network
    volumes:
      - /home:/home
      - /data:/data
      - ./conf/spark-env.sh:/spark/conf/spark-env.sh
      - ./conf/spark-defaults.conf:/spark/conf/spark-defaults.conf
  spark-worker:
    image: qwertyjack/spark
    depends_on:
      - spark-master
    command: >
      /bin/sh -c '
      /spark/sbin/start-slave.sh $$SPARK_MASTER
      && tail -f /spark/logs/*'
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    ports:
      - 8080
    networks:
      - spark-network
    volumes:
      - /home:/home
      - /data:/data

