version: '3.6'

services:
    nodemaster:
        image: mienkofax/spark-cluster:v0.8

    node2:
        image: mienkofax/spark-cluster:v0.8

    node3:
        image: mienkofax/spark-cluster:v0.8

    task:
        image: mienkofax/spark-cluster:v0.8
