version: "3.3"
networks:
  spark-network:
    ipam:
      driver: default
services:
  spark-master:
    image: qwertyjack/spark
    container_name: spark-master
    hostname: spark-master
    command:
      /spark/start-master.sh
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark-network
  spark-worker:
    image: qwertyjack/spark
    depends_on:
      - spark-master
    command:
      /spark/start-worker.sh
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    ports:
      - 8080
    networks:
      - spark-network

